version: "3"
services:
    cloudflared:
      image: visibilityspots/cloudflared
      hostname: cloudflared
      container_name: cloudflared
      restart: always
      cap_add:
        - NET_ADMIN
      networks:
        pihole_net:
          ipv4_address: 10.0.0.2
    pihole:
      image: pihole/pihole:latest
      hostname: pihole
      container_name: pihole
      restart: unless-stopped
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        - "80:80/tcp"
        - "443:443/tcp"
      environment:
        - DNS1='10.0.0.2#5054'
        - DNS2=''
        - DNSMASQ_LISTENING=all
        - IPv6=false
        - ServerIP=10.0.0.3 
        - TZ='America/Chicago'
        - WEBPASSWORD=${PIHOLE_PASSWD}
      volumes:
        - ${DATADIR}/etc-pihole:/etc/pihole
        - ${DATADIR}/etc-dnsmasq.d:/etc/dnsmasq.d
        # mdkir -p data/var/log/lighttpd
        # on Debian host
        # sudo chown -R www-data:www-data data/var/log/lighttpd
        # or
        # sudo chown -R 33:33 data/var/log/lighttpd
        - ${DATADIR}/var/log:/var/log
      dns:
        - 127.0.0.1
        #- 1.1.1.1
      cap_add:
        - NET_ADMIN
      networks:
        pihole_net:
          ipv4_address: 10.0.0.3

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
